name: Palo Alto Networks coverage

on:
  schedule:
    - cron: '0 */4 * * *'  # every 4 hours
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper script
        run: python .github/scrape_rss_news.py
        env:
          GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
          NEWSAPI_API_KEY: ${{ secrets.NEWSAPI_API_KEY }}

      - name: Complete
        run: echo "Scraper job finished successfully."
