name: Update PANW News Summaries

on:
  schedule:
    - cron: '0 */4 * * *'  # every 4 hours
  workflow_dispatch:
    inputs:
      backfill:
        description: "Run backfill mode"
        required: false
        default: "false"

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraping script
        run: |
          if [[ "${{ github.event.inputs.backfill }}" == "true" ]]; then
            python .github/scrape_rss_news.py --backfill
          else
            python .github/scrape_rss_news.py
          fi

      - name: Commit and push updates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          git add README.md summaries/weekly/summary.csv summaries/monthly/*/*

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            WEEK=$(date +%V)
            MONTH=$(date +%Y-%m)
            git commit -m "🗞️ Auto update: W${WEEK}, ${MONTH}"
            git push
          fi
