name: News Scraper

on:
  schedule:
    # Run every 4 hours
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  scrape-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python .github/scrape_rss_news.py

      - name: Debug summary files
        run: |
          echo "==== WEEKLY ===="
          head -n 5 summaries/weekly/summary.csv || echo "weekly missing"
          echo "==== MONTHLY ===="
          head -n 5 summaries/monthly/summary.csv || echo "monthly missing"
          echo "==== Git Status ===="
          git status

      - name: Commit & push changes if any
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update news coverage"
          branch: main
          file_pattern: |
            README.md
            summaries/**
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          skip_dirty_check: false
          push_options: '--force'
